#!/usr/bin/env python3

import argparse
import subprocess
import tempfile
import os


def getdatafile(db, query):
    """Exeecute query, save results to temp csv file, return its path"""
    fd, filepath = tempfile.mkstemp(suffix='.csv')
    p = subprocess.Popen(
        ['adosql', 'vfp', db],
        stdin=subprocess.PIPE,
        stdout=fd
    )
    p.communicate(input=query.encode('utf-8'))
    os.close(fd)
    return filepath


def main(db1, db2, query1, query2):
    file1 = getdatafile(db1, query1)
    file2 = getdatafile(db2, query2)
    subprocess.call(['daff', file1, file2])
    os.remove(file1)
    os.remove(file2)


def parse_args():
    p = argparse.ArgumentParser(
        description='Compare two database tables and print differences between them in highlighter diff format'
    )
    p.add_argument(
        'db1',
        help='path to first database'
    )
    p.add_argument(
        'db2',
        help='path to second database'
    )
    p.add_argument(
        'table1',
        help='table from the first database or an SQL SELECT query retrieving data from it'
    )
    p.add_argument(
        'table2',
        nargs='?',
        help='table from the second database or an SQL SELECT query retrieving data from it'
    )

    args = p.parse_args()
    args.table2 = args.table2 or args.table1
    return args


if __name__ == '__main__':
    args = parse_args()
    main(args.db1, args.db2, args.table1, args.table2)
