#!/usr/bin/env python3

import argparse
import subprocess
import sys


def main(srcdb, destdb, src_table, dest_table, target_table, key=None):
    diff = subprocess.Popen(
        ['tad-diff', '-typed-header'] +
        (['-key', key] if key else []) +
        [destdb, srcdb, dest_table, src_table],
        stdout=subprocess.PIPE
    )
    patch = subprocess.Popen(
        ['tad-patch'] +
        (['-key', key] if key else []) +
        [destdb, target_table],
        stdin=diff.stdout
    )
    # force flush to let writer receive SIGPIPE if reader dies while
    # writer is waiting with filled buffer, otherwise writer will wait
    # forever
    diff.stdout.close()
    return patch.wait()


def parse_args():
    p = argparse.ArgumentParser(
        description='Diff source and destination database tables, then patch destination to match source. Tables may be specified as SQL queries'
    )
    p.add_argument(
        '-key',
        help='comma-separated list of column names to use as a key when diffing and while building DELETE and UPDATE queries when patching'
    )
    p.add_argument(
        'src_db',
        help='path to source database'
    )
    p.add_argument(
        'dest_db',
        help='path to destination database'
    )
    p.add_argument(
        'src_table',
        help='table in the source database or an SQL query retrieving data set from it. If contains no spaces assumed to be a table name and replaced with "SELECT * from <src_table>", otherwise untouched'
    )
    p.add_argument(
        'dest_table',
        nargs='?',
        help='same as src_table but for the destination database. If omitted takes value of src_table'
    )
    p.add_argument(
        '-target-table',
        help='table in the destination database to patch. Used when dest_table is a query'
    )

    args = p.parse_args()
    args.dest_table = args.dest_table or args.src_table
    args.target_table = args.target_table or args.dest_table
    return args


if __name__ == '__main__':
    args = parse_args()
    sys.exit(main(
        args.src_db,
        args.dest_db,
        args.src_table,
        args.dest_table,
        args.target_table,
        args.key
    ))
